### ISSUE TITLE
建议增加打卡时间间隔，叔叔疑似会检测了

### ISSUE THREAD

**Issue by ClayStan** [XiaoMiku01/bili-live-heart#49]
错误日志:
A-SOUL_Official(703007996)直播间打卡失败: 您发送弹幕的频率过快

2022-03-29 12:12:55,107 - apscheduler.executors.default - INFO - Job "main (trigger: cron[month='*', day='*', day_of_week='*', hour='0', minute='0'], next run at: 2022-03-30 00:00:00 EDT)" executed successfully
^CTraceback (most recent call last):
  File "/root/bili-live-heart/./index.py", line 70, in <module>
    schedulers.start()
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/schedulers/blocking.py", line 21, in start
    self._main_loop()
  File "/usr/local/lib/python3.10/dist-packages/apscheduler/schedulers/blocking.py", line 30, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib/python3.10/threading.py", line 600, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

**Comment by ClayStan** [comment]
那可能是我多个设备同时打卡了吧，手机在看直播发弹幕，电脑在跑脚本，我再多试试，该 issue 关闭
